export enum MusclePrimary {
  Abs = 'abs',
  Abductors = 'abductors',
  Adductors = 'adductors',
  Forearms = 'forearms',
  Biceps = 'biceps',
  Cardio = 'cardio',
  Quadriceps = 'quadriceps',
  FullBody = 'full-body',
  Bibs = 'bibs',
  LowerBack = 'lower-back',
  HighBack = 'high-back',
  LegCufflinks = 'leg-cufflinks',
  Buttocks = 'buttocks',
  Shoulders = 'shoulders',
  Hamstrings = 'hamstrings',
  Neck = 'neck',
  Chest = 'chest',
  Trapeze = 'trapeze',
  Triceps = 'triceps',
  Other = 'other',
}
